version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.16
      - image: circleci/node:14
    environment:
      SONAR_TOKEN: eea8bec81489972faf09e2fba4048155f45adab7
      SONAR_PROJECT_KEY: dhanu0001
      SONAR_ORGANIZATION: dhanu0001

    steps:
      - checkout
      # - run:
      #     name: Install dependencies
      #     command: npm ci
      # - run:
      #     name: Run tests
      #     command: npm test
      - run:
          name: Install SonarCloud CLI
          command: |
            curl -LJO https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
            unzip sonar-scanner-cli-4.5.0.2216-linux.zip
            rm sonar-scanner-cli-4.5.0.2216-linux.zip
            export PATH=$PATH:$PWD/sonar-scanner-4.5.0.2216-linux/bin
      - run:
          name: Scan with SonarCloud
          command: |
            cd /home/circleci/project/
            ls -lrt /home/circleci/project/
            ./sonar-scanner-4.5.0.2216-linux/bin/sonar-scanner \
              -Dsonar.login=eea8bec81489972faf09e2fba4048155f45adab7 \
              -Dsonar.organization=dhanu0001 \
              -Dsonar.projectKey=dhanu0001 \
              -Dsonar.sources=. \
              -Dsonar.host.url=https://sonarcloud.io