version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:11.0.16
    steps:
      - checkout
      - run:
          name: Install SonarScanner
          command: |
            wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip
            unzip sonar-scanner-cli-4.5.0.2216-linux.zip
            rm sonar-scanner-cli-4.5.0.2216-linux.zip
      - run:
          name: Run SonarScanner
          command: |
            ./sonar-scanner-4.5.0.2216-linux/bin/sonar-scanner \
              # -Dsonar.projectKey=<your-sonarcloud-project-key> \
              -Dsonar.organization=dhanu0001
              -Dsonar.host.url=https://sonarcloud.io \
              -Dsonar.login=eea8bec81489972faf09e2fba4048155f45adab7
